#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tilix
Version  : 1.9.3
Release  : 1
URL      : https://github.com/gnunn1/tilix/archive/1.9.3.tar.gz
Source0  : https://github.com/gnunn1/tilix/archive/1.9.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-3.0-only MPL-2.0
Requires: tilix-bin = %{version}-%{release}
Requires: tilix-data = %{version}-%{release}
Requires: tilix-license = %{version}-%{release}
Requires: tilix-locales = %{version}-%{release}
BuildRequires : GtkD-dev
BuildRequires : appstream-glib
BuildRequires : buildreq-meson
BuildRequires : desktop-file-utils
BuildRequires : gdk-pixbuf-dev
BuildRequires : glib-dev
BuildRequires : ldc-dev
BuildRequires : pkgconfig(libunwind)
BuildRequires : pkgconfig(x11)
Patch1: 001-fix-meson-build.patch

%description
[![Build Status](https://travis-ci.org/gnunn1/tilix.svg?branch=master)](https://travis-ci.org/gnunn1/tilix)
[![Translation status](https://hosted.weblate.org/widgets/tilix/-/svg-badge.svg)](https://hosted.weblate.org/engage/tilix/?utm_source=widget)
# Tilix
A tiling terminal emulator for Linux using GTK+ 3. The Tilix web site for users is available at [https://gnunn1.github.io/tilix-web](https://gnunn1.github.io/tilix-web).

%package bin
Summary: bin components for the tilix package.
Group: Binaries
Requires: tilix-data = %{version}-%{release}
Requires: tilix-license = %{version}-%{release}

%description bin
bin components for the tilix package.


%package data
Summary: data components for the tilix package.
Group: Data

%description data
data components for the tilix package.


%package license
Summary: license components for the tilix package.
Group: Default

%description license
license components for the tilix package.


%package locales
Summary: locales components for the tilix package.
Group: Default

%description locales
locales components for the tilix package.


%prep
%setup -q -n tilix-1.9.3
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567871490
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang tilix
## install_append content
mkdir -p %{buildroot}/usr/share/package-licenses/tilix
cp LICENSE %{buildroot}/usr/share/package-licenses/tilix/LICENSE
cp -a data/icons/LICENSE %{buildroot}/usr/share/package-licenses/tilix/LICENSE-data-icons
cp -a source/x11/LICENSE %{buildroot}/usr/share/package-licenses/tilix/LICENSE-source-x11
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tilix

%files data
%defattr(-,root,root,-)
/usr/share/applications/com.gexperts.Tilix.desktop
/usr/share/dbus-1/services/com.gexperts.Tilix.service
/usr/share/glib-2.0/schemas/com.gexperts.Tilix.gschema.xml
/usr/share/icons/hicolor/scalable/apps/com.gexperts.Tilix.svg
/usr/share/icons/hicolor/symbolic/apps/com.gexperts.Tilix-symbolic.svg
/usr/share/metainfo/com.gexperts.Tilix.appdata.xml
/usr/share/nautilus-python/extensions/open-tilix.py
/usr/share/tilix/resources/tilix.gresource
/usr/share/tilix/schemes/base16-twilight-dark.json
/usr/share/tilix/schemes/linux.json
/usr/share/tilix/schemes/material.json
/usr/share/tilix/schemes/monokai.json
/usr/share/tilix/schemes/orchis.json
/usr/share/tilix/schemes/solarized-dark.json
/usr/share/tilix/schemes/solarized-light.json
/usr/share/tilix/schemes/tango.json
/usr/share/tilix/scripts/tilix_int.sh

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/tilix/LICENSE
/usr/share/package-licenses/tilix/LICENSE-data-icons
/usr/share/package-licenses/tilix/LICENSE-source-x11

%files locales -f tilix.lang
%defattr(-,root,root,-)

